name: Lint and build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-lint-build:
    name: Run ESLint and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Pack
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: functional-try.tgz
          path: functional-try-*.tgz
