name: Lint and build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-lint-build:
    name: Run ESLint and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Pack
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functional-try-${{ github.ref_name }}.${{ github.sha }}.tgz
          path: functional-try-*.tgz
